services:
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: trimly
      POSTGRES_PASSWORD: trimly24291406
      POSTGRES_DB: trimly
    ports:
      - "5432:5432"
    volumes:
      - trimly-pgdata:/var/lib/postgresql/data
    networks:
      - trimly-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - trimly-network

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "trimly-redis@2429"
    
networks:
  trimly-network:

volumes:
  trimly-pgdata:
  redis_data: